# Generated by Django 3.2.6 on 2021-08-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='apartment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='floor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='intime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='mobileno',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='outtime',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='reasontomeet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='remark',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='vdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitorname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='whomtomeet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
